sudo: required

language: ruby

services:
  - docker

env:
  - DIR=.    VERSION=latest
  - DIR=.    VERSION=5.4
  - DIR=.    VERSION=5.5
  - DIR=.    VERSION=5.6
  - DIR=.    VERSION=7.0
  - DIR=dev/ VERSION=latest
  - DIR=dev/ VERSION=5.5
  - DIR=dev/ VERSION=5.6

before_install:
- make -C ${DIR} pull VERSION=${VERSION}

install:
- make -C ${DIR} build-nopull VERSION=${VERSION}

script:
- make -C ${DIR} test VERSION=${VERSION}
